server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Tenta achar o arquivo exato. Se não achar, devolve o index.html
        try_files $uri $uri/ /index.html;
    }
}