name: Pipeline Web Angular

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-sonar-push:
    runs-on: ubuntu-latest

    steps:
    # 1. Baixa o código para a máquina do GitHub
    - name: Checkout do código
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 2. Prepara o ambiente Node.js na versão 20
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    # 3. Instala as dependências do package.json
    - name: Instalar Dependências
      run: npm install

    # 4. Roda os testes do Angular em modo invisível (Headless)
    - name: Rodar Testes
      run: npm run test -- --watch=false --browsers=ChromeHeadless

    # 5. Análise de Qualidade do Código no SonarCloud
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=turisco-tech_poc-agenda-web
          -Dsonar.organization=turisco-tech
          -Dsonar.sources=src
          -Dsonar.tests=src
          -Dsonar.test.inclusions=**/*.spec.ts
          -Dsonar.exclusions=**/node_modules/**,**/*.spec.ts

    # 6. Autenticação na AWS
    - name: Configurar Credenciais AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # 7. Login no cofre (ECR)
    - name: Login no Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # 7.5 NOVO PASSO: Injetar IP da EC2 no Angular ANTES do Build do Docker
    - name: Injetar IP da EC2 no Angular
      env:
        API_URL: ${{ secrets.API_URL }}
      run: |
        echo "Injetando a URL da API no environment de produção..."
        sed -i "s|API_URL|$API_URL|g" src/environments/environment.prod.ts

    # 8. Multi-stage Docker Build e Push (Aqui dentro roda o npm run build do Angular)
    - name: Build, Tag, e Push da Imagem Docker
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: poc-agenda-web
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

    # 9. Coleta de logs críticos em caso de falha
    - name: Tratamento de Erros e Logs Críticos
      if: failure()
      run: |
        echo "::error::Falha detectada na esteira do Web! Coletando logs..."
        docker system df
        docker ps -a

    # 10. Injeta a nova imagem Docker no JSON do Frontend
    - name: Preencher o novo ID da imagem na Task Definition
      id: render-task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: .aws/task-definition.json
        container-name: web-container
        image: ${{ steps.login-ecr.outputs.registry }}/poc-agenda-web:${{ github.sha }}

    # 11. Atualiza o Serviço ECS na AWS
    - name: Deploy da nova Task Definition Web no Amazon ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.render-task-def.outputs.task-definition }}
        service: poc-agenda-web-service
        cluster: poc-agenda-cluster
        wait-for-service-stability: true